[tool.poetry]
name = "Horizon Builder"
version = "v0.0.1"
description = "Attempt at a DnD 5e Character builder inspired by Aurora Builder."
authors = ["GustavoSchip <gustavoschip@proton.me>"]
repository = "https://github.com/Horizon-Builder/Horizon-Builder"
documentation = "https://horizon-builder.github.io/Horizon-Builder/"
readme = "README.md"
package-mode = false
license = "LICENSE"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
flask = "^3.0.2"
click = "^8.1.7"
PyYAML = "^6.0.1"
Werkzeug = "^3.0.1"
pyopenssl = "^24.0.0"
pydantic = "^2.6.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
deptry = "^0.12.0"
mypy = "^1.5.1"
pre-commit = "^3.4.0"
types-PyYAML = "^6.0.12.12"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocs-material = "^9.2.7"
mkdocstrings = { extras = ["python"], version = "^0.23.0" }

[tool.mypy]
files = ["src"]
disallow_untyped_defs = "True"
disallow_any_unimported = "True"
no_implicit_optional = "True"
check_untyped_defs = "True"
warn_return_any = "True"
warn_unused_ignores = "True"
show_error_codes = "True"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.deptry.per_rule_ignores]
DEP001 = ["main", "server", "parser", "plugins", "endpoints", "interfaces", "api_actions"]
DEP002 = ["pyopenssl"]

[tool.ruff]
target-version = "py311"
line-length = 120
fix = true
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
    # UsePEP604Annotation
    "UP007",
]

[tool.ruff.format]
preview = true

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["src"]


[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]
