blank_issues_enabled: false
contact_links:
  - name: Horizon Builder documentation
    url: https://horizon-builder.github.io/Horizon-Builder/
    about: Please do reasearch here before posting an issue.
