engine:
  version: 1
  content:
    content_folder: ./content/
  characters: # TODO: Implement...
    characters_folder: ./characters/ # TODO: Implement...
  plugins: # TODO: Implement...
    plugins_folder: ./plugins/ # TODO: Implement...
    enabled: false # TODO: Implement...
  web:
    address: 127.0.0.1
    port: 80
