engine:
  version: 1 # TODO: Implement...
  content:
    content_folder: ./content/
    type: yml # Can be xml or yml  # TODO: Implement...
    compatibility: false # Can be Aurora or false  # TODO: Implement...
  plugins: # TODO: Implement...
    plugin_folder: ./plugins/ # TODO: Implement...
    enabled: false # TODO: Implement...
  web:
    address: 127.0.0.1
    port: 80
