on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
    types: [ "opened", "synchronize", "reopened", "ready_for_review" ]
  workflow_dispatch:
concurrency: "${{ github.workflow }}-${{ github.ref }}"
jobs:
  check:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@main"
      - name: "Set up PDM"
        uses: "pdm-project/setup-pdm@main"
        with:
          cache: "true"
          python-version: "${{ matrix.python-version }}"
          update-python: "true"
      - name: "Install Dependencies"
        run: "pdm install --no-self --no-editable --check --fail-fast"
  pre-commit:
    runs-on: "ubuntu-latest"
    if: "${{ github.event_name == 'pull_request' }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@main"
      - name: "Set up PDM"
        uses: "pdm-project/setup-pdm@main"
        with:
          cache: "true"
          python-version: "3.11"
          update-python: "true"
      - name: "Cache pre-commit"
        uses: "actions/cache@main"
        with:
          path: "~/.cache/pre-commit"
          key: "pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}"
      - name: "Run pre-commit lite"
        uses: "pre-commit-ci/lite-action@main"
        if: "${{ always() }}"
      - name: "Run pre-commit"
        uses: "pre-commit/action@main"
