name: release-master

on:
  release:
    types: [published]
    branches: [master, dev]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Deploy documentation
        run: poetry run mkdocs gh-deploy --force

  pyinstaller:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup options for PyInstaller
        shell: pwsh
        id: config
        run: |
          echo "OPTIONS=$(make options)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "SPEC=$(make spec)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "OS=$(make os)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.11"
          spec: "${{ steps.config.outputs.SPEC }}"
          requirements: "src/requirements.txt"
          upload_exe_with_name: "Horizon Builder ${{ steps.config.outputs.OS }}_${{ runner.arch }}_${{ github.ref_name }}"
          options: ${{ steps.config.outputs.OPTIONS }}
